### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by bajki** [vedmant/laravel-shortcodes#7]
Hi, 
if i register div shortcode i get strange output..
Lets say if i want render:
[div class="row"][div class="col-12"]Some text[/div][/div] 
i get:
<div class="row">Some text</div>[/div]

**Comment by vedmant** [comment]
@bajki There is limitation with the same shortcodes nesting, https://stackoverflow.com/questions/13184085/is-it-possible-to-nest-wordpress-shortcodes-that-are-the-same-shortcode

It's better if you make something like this:

```
[row]
   [col size="12"]
      Some text
   [/col]
[/row]
```
